name: Commander
version: 1.0
description: |
      Using a given set of regexes, this plugin allows command aliases and chat censoring.
author: Tustin2121
main: org.digiplex.bukkitplugin.commander.CommanderPlugin
commands:
   commander:
      description: The main commander command
      usage: /<command> [Reload]

